version: '3.9'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD

  phpmyadmin:
    image: phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      PMA_USER: $DB_USER
      PMA_PASSWORD: $DB_PASSWORD

  frontend:
    build:
      context: .
      dockerfile: ./Frontend.Dockerfile
    ports:
      - '3003:3003'
    environment:
      VITE_BACKEND_URL: $VITE_BACKEND_URL

  backend:
    build:
      context: .
      dockerfile: ./Backend.Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - mysql
    restart: on-failure:10
    environment:
      DB_HOST: mysql
      DB_USER: $DB_USER
      DB_PASS: $DB_PASSWORD
      DB_NAME: $DB_NAME
      FRONTEND_URL: $FRONTEND_URL
      BACKEND_URL: $BACKEND_URL
      JWT_SECRET: $JWT_SECRET
      EMAIL_USERNAME: $GMAIL_USERNAME
      EMAIL_PASSWORD: $GMAIL_PASSWORD