version: '3.9'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD

  phpmyadmin:
    image: phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      PMA_USER: $DB_USER
      PMA_PASSWORD: $DB_PASSWORD

  redis:
    image: redis:latest
    restart: always
    ports:
      - "$REDIS_PORT:$REDIS_PORT"
    environment:
      - REDIS_PASSWORD= $REDIS_PASSWORD
      - REDIS_PORT= $REDIS_PORT
      - REDIS_DATABASES= $REDIS_DATABASES